function severityStyle(sev) {
  if (sev === "high")   return { background:"#fdf0ec", color:C.rust,  borderColor:"#e8b090" };
  if (sev === "medium") return { background:"#fdf8ec", color:"#a07020", borderColor:"#e0c880" };
  return                       { background:"#f0f4ee", color:C.sage,  borderColor:"#b5c4ae" };
}

// Helper for confidence band coloring on the appraisal card
function confidenceBandStyle(band) {
  if (band === "High")         return { color:"#3a6b38" };
  if (band === "Moderate")     return { color:"#7a6010" };
  if (band === "Low")          return { color:C.rust    };
  if (band === "Inconclusive") return { color:"#888"    };
  return {};
}

// Helper for effective_confidence color coding in visual scan table
function confColor(eff) {
  if (eff >= 0.7) return { color: C.sage,   fontWeight: 600 };
  if (eff >= 0.4) return { color: C.bronze, fontWeight: 600 };
  return                 { color: "#bbb" };
}

// ============================================================
// STYLES
// ============================================================
const C = {
  parchment: "#f5efe4", cream: "#faf6ef", ink: "#1a1410",
  sepia: "#4a3728", bronze: "#8b6914", rust: "#c0703a",
  sage: "#5a6b52", divider: "#d4c9b4", card: "#fdfaf4",
  shadow: "rgba(26,20,16,0.10)",
};
const S = {
  root:        { minHeight:"100vh", background:C.cream, fontFamily:"'Georgia','Times New Roman',serif", color:C.ink, position:"relative", overflowX:"hidden" },
  bgTexture:   { position:"fixed", inset:0, backgroundImage:`radial-gradient(circle at 18% 18%, rgba(139,105,20,0.05) 0%, transparent 55%), radial-gradient(circle at 82% 82%, rgba(90,107,82,0.04) 0%, transparent 55%)`, pointerEvents:"none", zIndex:0 },
  header:      { borderBottom:`1px solid ${C.divider}`, background:C.ink, position:"sticky", top:0, zIndex:100 },
  headerInner: { maxWidth:1160, margin:"0 auto", padding:"12px 20px", display:"flex", alignItems:"center", justifyContent:"space-between" },
  logoArea:    { display:"flex", alignItems:"center", gap:12, cursor:"pointer" },
  logoMark:    { fontSize:24, color:C.bronze },
  logoName:    { fontSize:18, fontWeight:700, letterSpacing:"0.12em", color:C.parchment },
  logoSub:     { fontSize:9, color:C.bronze, letterSpacing:"0.18em", textTransform:"uppercase", marginTop:1, fontFamily:"sans-serif" },
  caseTagArea: { display:"flex", alignItems:"center", gap:8 },
  caseIdText:  { fontSize:11, color:"#888", fontFamily:"monospace" },
  stepChip:    { fontSize:10, background:C.bronze, color:C.ink, padding:"3px 9px", borderRadius:2, letterSpacing:"0.1em", fontFamily:"sans-serif" },
  main:        { position:"relative", zIndex:1 },
  centered:    { minHeight:"calc(100vh - 56px)", display:"flex", alignItems:"center", justifyContent:"center", padding:"32px 20px" },
  introCard:   { maxWidth:560, textAlign:"center", width:"100%" },
  introEra:    { fontSize:10, letterSpacing:"0.22em", textTransform:"uppercase", color:C.bronze, marginBottom:16, fontFamily:"sans-serif" },
  introTitle:  { fontSize:"clamp(32px, 8vw, 52px)", lineHeight:1.1, margin:"0 0 18px", fontWeight:400, letterSpacing:"-0.01em" },
  introDesc:   { fontSize:15, lineHeight:1.75, color:C.sepia, marginBottom:24 },
  phasePillRow:{ display:"flex", flexWrap:"wrap", gap:6, justifyContent:"center", marginBottom:28 },
  phasePill:   { fontSize:10, letterSpacing:"0.08em", textTransform:"uppercase", border:`1px solid ${C.divider}`, color:C.sepia, padding:"4px 10px", borderRadius:2, fontFamily:"sans-serif" },
  ctaBtn:      { display:"inline-block", background:C.ink, color:C.parchment, border:"none", padding:"14px 32px", fontSize:14, letterSpacing:"0.08em", cursor:"pointer", fontFamily:"'Georgia',serif", borderRadius:2 },
  ctaDisabled: { background:C.divider, color:C.sepia, cursor:"not-allowed" },
  versionNote: { fontSize:10, color:C.divider, marginTop:12, fontFamily:"sans-serif" },

  // ── Mode selector (landing page) ──────────────────────────────
  modeGrid:        { display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:24, width:"100%", maxWidth:560 },
  modeCard:        { background:C.card, border:`1.5px solid ${C.divider}`, borderRadius:6, padding:"20px 18px", cursor:"pointer", display:"flex", flexDirection:"column", gap:10, transition:"border-color 0.2s", textAlign:"left" },
  modeCardTop:     { display:"flex", alignItems:"center", justifyContent:"space-between" },
  modeIcon:        { fontSize:22, lineHeight:1 },
  modeBadge:       { fontSize:9, letterSpacing:"0.14em", textTransform:"uppercase", background:C.parchment, border:`1px solid ${C.divider}`, color:C.sepia, padding:"2px 8px", borderRadius:2, fontFamily:"sans-serif" },
  modeCardTitle:   { fontSize:18, fontWeight:400, color:C.ink, lineHeight:1.2 },
  modeCardContext: { fontSize:10, color:C.bronze, fontFamily:"sans-serif", letterSpacing:"0.04em", marginTop:-4 },
  modeCardDesc:    { fontSize:12, color:C.sepia, lineHeight:1.6, fontFamily:"sans-serif" },
  modeOutputList:  { display:"flex", flexDirection:"column", gap:5, margin:"4px 0" },
  modeOutputItem:  { display:"flex", alignItems:"flex-start", gap:7, fontSize:12, color:C.sepia, fontFamily:"sans-serif" },
  modeOutputDot:   { color:C.bronze, fontSize:8, flexShrink:0, marginTop:3 },
  modeTime:        { fontSize:10, color:"#aaa", fontFamily:"sans-serif", letterSpacing:"0.06em" },
  modeBtn:         { padding:"10px 0", fontSize:13, fontFamily:"'Georgia',serif", borderRadius:2, textAlign:"center", marginTop:4 },
  modeBtnQuick:    { background:"#3a6b38", color:"#fff" },
  modeBtnFull:     { background:C.ink, color:C.parchment },

  // ── Quick Mode intake ─────────────────────────────────────────
  quickPage:          { maxWidth:480, margin:"0 auto", padding:"32px 20px 48px", display:"flex", flexDirection:"column", gap:20 },
  quickHeader:        { textAlign:"center" },
  quickModeBadge:     { display:"inline-block", fontSize:11, letterSpacing:"0.12em", textTransform:"uppercase", background:"#edf5ec", border:"1px solid #a8cca6", color:"#3a6b38", padding:"3px 12px", borderRadius:2, fontFamily:"sans-serif", marginBottom:10 },
  quickTitle:         { fontSize:26, fontWeight:400, margin:"0 0 8px", color:C.ink },
  quickSubtitle:      { fontSize:14, color:C.sepia, lineHeight:1.6, margin:0 },
  quickPhotoGrid:     { display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:10 },
  quickSlot:          { border:`1.5px dashed ${C.divider}`, borderRadius:4, padding:14, background:C.card, display:"flex", flexDirection:"column", gap:8, minHeight:130, alignItems:"center", justifyContent:"center", textAlign:"center" },
  quickSlotFilled:    { border:`1.5px solid #a8cca6`, background:"#f0f5ef", borderRadius:4, padding:10, display:"flex", flexDirection:"column", alignItems:"center", gap:6 },
  quickThumb:         { width:"100%", height:80, objectFit:"cover", borderRadius:2 },
  quickSlotCheck:     { fontSize:11, color:"#3a6b38", fontFamily:"sans-serif", fontWeight:600 },
  quickSlotLabel:     { fontSize:12, fontWeight:600, color:C.sepia, fontFamily:"sans-serif" },
  quickSlotHint:      { fontSize:10, color:"#aaa", fontFamily:"sans-serif", lineHeight:1.4 },
  quickUploadRow:     { display:"flex", gap:6, width:"100%" },
  quickUploadBtn:     { flex:1, background:"none", border:`1px solid ${C.divider}`, padding:"6px 0", fontSize:10, cursor:"pointer", borderRadius:2, color:C.sepia, fontFamily:"sans-serif" },
  quickCount:         { fontSize:12, color:C.sepia, fontFamily:"sans-serif", textAlign:"center" },
  quickGuessBlock:    { display:"flex", flexDirection:"column", gap:6 },
  quickGuessLabel:    { fontSize:12, fontWeight:600, color:C.sepia, fontFamily:"sans-serif" },
  quickGuessInput:    { border:`1px solid ${C.divider}`, background:C.card, padding:"10px 12px", fontSize:14, color:C.ink, fontFamily:"'Georgia',serif", borderRadius:2 },
  quickError:         { background:"#fdf0ec", border:`1px solid ${C.rust}`, color:C.rust, padding:"10px 14px", borderRadius:2, fontSize:13, fontFamily:"sans-serif" },
  quickErrorCard:     { background:"#fdf0ec", border:`1.5px solid #d8a090`, borderRadius:4, padding:"14px 16px", display:"flex", flexDirection:"column", gap:8 },
  quickErrorMsg:      { fontSize:14, color:"#8b3a2a", lineHeight:1.6, fontFamily:"'Georgia',serif" },
  quickErrorDebugBtn: { background:"none", border:`1px solid #d8a090`, color:"#8b3a2a", padding:"4px 10px", fontSize:10, cursor:"pointer", borderRadius:2, fontFamily:"sans-serif", letterSpacing:"0.06em", alignSelf:"flex-start" },
  quickErrorDebugPanel:{ background:"rgba(26,20,16,0.04)", border:`1px solid ${C.divider}`, borderRadius:2, padding:"10px 12px", display:"flex", flexDirection:"column", gap:6 },
  quickErrorDebugLine:{ fontSize:11, color:C.sepia, fontFamily:"sans-serif" },
  quickErrorRaw:      { fontSize:10, color:C.sepia, fontFamily:"monospace", whiteSpace:"pre-wrap", wordBreak:"break-word", margin:0, maxHeight:140, overflowY:"auto" },
  quickPriceRow:      { display:"flex", alignItems:"center", gap:0 },
  quickPriceDollar:   { fontSize:15, color:C.sepia, padding:"9px 8px 9px 12px", background:C.parchment, border:`1px solid ${C.divider}`, borderRight:"none", borderRadius:"2px 0 0 2px", lineHeight:1 },
  quickPriceInput:    { flex:1, border:`1px solid ${C.divider}`, borderLeft:"none", background:C.card, padding:"9px 12px 9px 4px", fontSize:15, color:C.ink, fontFamily:"'Georgia',serif", borderRadius:"0 2px 2px 0", outline:"none" },
  quickValueRange:    { fontSize:22, color:C.ink, fontWeight:400, marginBottom:8 },
  quickAskingRow:     { display:"flex", alignItems:"center", gap:12, paddingTop:10, borderTop:`1px solid ${C.divider}` },
  quickAskingBox:     { flex:1 },
  quickPriceGuidanceBadge:{ fontSize:13, fontWeight:700, fontFamily:"sans-serif", letterSpacing:"0.08em", padding:"6px 14px", borderRadius:3, border:"1.5px solid", flexShrink:0 },

  // ── Progressive photo capture ─────────────────────────────────
  progressiveCaptureBlock:  { display:"flex", flexDirection:"column", gap:10 },
  progressiveScanning:      { display:"flex", alignItems:"center", gap:10, background:"#fdf8ec", border:"1px solid #d8c870", borderRadius:3, padding:"10px 14px", fontSize:13, color:"#7a6010", fontFamily:"sans-serif" },
  progressiveScanningDot:   { fontSize:16, animation:"none" },
  progressiveSuggestion:    { background:"#f5f8f4", border:"1px solid #c8d8c0", borderRadius:4, padding:"14px 16px" },
  progressiveSuggestionTitle:{ fontSize:11, letterSpacing:"0.12em", textTransform:"uppercase", color:"#3a6b38", fontFamily:"sans-serif", marginBottom:10 },
  progressiveSuggestionList: { display:"flex", flexDirection:"column", gap:10 },
  progressiveSuggestionItem: { display:"flex", alignItems:"flex-start", justifyContent:"space-between", gap:10 },
  progressiveSuggestionLabel:{ fontSize:13, color:C.ink, fontFamily:"'Georgia',serif", lineHeight:1.4 },
  progressiveSuggestionHint: { fontSize:10, color:"#888", fontFamily:"sans-serif", marginTop:2 },
  progressiveAddBtns:        { display:"flex", gap:6, flexShrink:0 },
  progressiveMiniBtn:        { background:"none", border:`1px solid ${C.divider}`, width:32, height:32, cursor:"pointer", borderRadius:2, fontSize:14, display:"flex", alignItems:"center", justifyContent:"center" },
  progressivePhotoCount:     { fontSize:10, color:"#aaa", fontFamily:"sans-serif", marginTop:10, textAlign:"right" },
  progressiveAddBlock:       { background:C.card, border:`1px solid ${C.divider}`, borderRadius:4, padding:"14px 16px" },
  progressiveAddTitle:       { fontSize:13, color:C.bronze, fontFamily:"sans-serif", fontWeight:600, marginBottom:4 },
  progressiveAddHint:        { fontSize:11, color:"#aaa", fontFamily:"sans-serif", marginBottom:10 },
  quickAnalyzeBtn:    { background:"#3a6b38", color:"#fff", border:"none", padding:"16px", fontSize:15, cursor:"pointer", fontFamily:"'Georgia',serif", borderRadius:3, textAlign:"center" },
  quickAnalyzeBtnDisabled:{ background:C.divider, color:C.sepia, cursor:"not-allowed" },

  // ── Quick Mode results ────────────────────────────────────────
  quickResultPage:    { maxWidth:480, margin:"0 auto", padding:"24px 20px 48px", display:"flex", flexDirection:"column", gap:16 },
  signalCard:         { border:"2px solid", borderRadius:6, padding:"18px 20px", display:"flex", alignItems:"flex-start", gap:14 },
  signalIndicator:    { fontSize:28, lineHeight:1, flexShrink:0 },
  signalBody:         { flex:1 },
  signalLabel:        { fontSize:18, fontWeight:700, fontFamily:"sans-serif", marginBottom:6 },
  signalRationale:    { fontSize:13, color:C.sepia, lineHeight:1.6, fontFamily:"'Georgia',serif" },
  quickResultBlock:   { background:C.card, border:`1px solid ${C.divider}`, borderRadius:4, padding:"16px 18px" },
  quickResultBlockTitle:{ fontSize:10, letterSpacing:"0.16em", textTransform:"uppercase", color:C.bronze, fontFamily:"sans-serif", marginBottom:8 },
  quickResultId:      { fontSize:20, color:C.ink, fontWeight:400, lineHeight:1.3 },
  quickResultSub:     { fontSize:12, color:C.sepia, fontFamily:"sans-serif", marginTop:4 },
  quickMetaRow:       { display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 },
  quickMetaBox:       { background:C.card, border:`1px solid ${C.divider}`, borderRadius:4, padding:"14px 16px" },
  quickMetaLabel:     { fontSize:10, letterSpacing:"0.12em", textTransform:"uppercase", color:C.sepia, fontFamily:"sans-serif", marginBottom:5 },
  quickMetaValue:     { fontSize:16, color:C.ink, fontWeight:400 },
  quickClueRow:       { display:"flex", flexWrap:"wrap", gap:7 },
  quickClue:          { fontSize:11, background:C.parchment, border:`1px solid ${C.divider}`, color:C.ink, padding:"4px 10px", borderRadius:2, fontFamily:"sans-serif" },
  quickNoteList:      { listStyle:"none", padding:0, margin:0, display:"flex", flexDirection:"column", gap:7 },
  quickNoteItem:      { display:"flex", alignItems:"flex-start", gap:8, fontSize:13, color:C.sepia, lineHeight:1.6 },
  quickNoteDot:       { color:C.bronze, fontSize:10, flexShrink:0, marginTop:3 },
  quickHardNeg:       { background:"#fdf0ec", border:`1px solid #e8b090`, borderRadius:4, padding:"14px 16px" },
  quickHardNegTitle:  { fontSize:12, color:C.rust, fontFamily:"sans-serif", fontWeight:600, marginBottom:6 },
  quickHardNegItem:   { fontSize:12, color:C.sepia, fontFamily:"sans-serif", marginTop:4 },
  upgradeBlock:       { background:"#f5f8f4", border:`1px solid #c8d8c0`, borderRadius:4, padding:"18px 20px", display:"flex", flexDirection:"column", gap:10 },
  upgradeTitle:       { fontSize:14, fontWeight:600, color:C.ink, fontFamily:"'Georgia',serif" },
  upgradeDesc:        { fontSize:12, color:C.sepia, lineHeight:1.6, fontFamily:"sans-serif" },
  upgradeHints:       { display:"flex", flexWrap:"wrap", gap:7 },
  upgradeHint:        { fontSize:10, color:"#3a6b38", background:"#edf5ec", border:"1px solid #a8cca6", padding:"2px 9px", borderRadius:2, fontFamily:"sans-serif" },
  upgradeBtn:         { background:C.ink, color:C.parchment, border:"none", padding:"12px", fontSize:13, cursor:"pointer", fontFamily:"'Georgia',serif", borderRadius:2, textAlign:"center" },
  quickNewScanBtn:    { background:"none", border:`1px solid ${C.divider}`, padding:"10px", fontSize:13, cursor:"pointer", color:C.sepia, fontFamily:"'Georgia',serif", borderRadius:2, textAlign:"center" },
  intakePage:  { maxWidth:680, margin:"0 auto", padding:"0 0 40px" },
  // Evidence info panel
  evidenceInfoPanel:  { margin:"20px 20px 0", padding:"16px 20px", background:C.parchment, border:`1px solid ${C.divider}`, borderRadius:6 },
  evidenceInfoTitle:  { fontSize:11, letterSpacing:"0.16em", textTransform:"uppercase", color:C.bronze, fontFamily:"sans-serif", marginBottom:12 },
  evidenceInfoList:   { listStyle:"none", padding:0, margin:"0 0 12px", display:"grid", gridTemplateColumns:"1fr 1fr", gap:"6px 12px" },
  evidenceInfoItem:   { display:"flex", alignItems:"center", gap:7, fontSize:13, color:C.sepia },
  evidenceInfoCheck:  { color:C.sage, flexShrink:0, fontSize:12, fontWeight:700 },
  evidenceInfoFooter: { fontSize:12, color:"#aaa", fontFamily:"sans-serif", fontStyle:"italic", borderTop:`1px solid ${C.divider}`, paddingTop:10, marginTop:4 },
  intakeSection:{ padding:"28px 20px 0" },
  sectionLabel:{ fontSize:10, letterSpacing:"0.22em", textTransform:"uppercase", color:C.bronze, marginBottom:5, fontFamily:"sans-serif" },
  sectionTitle:{ fontSize:22, fontWeight:400, margin:"0 0 8px", lineHeight:1.2 },
  sectionDesc: { fontSize:13, lineHeight:1.7, color:C.sepia, marginBottom:20 },
  photoStack:  { display:"flex", flexDirection:"column", gap:12 },
  // Core group header
  coreGroupHeader: { display:"flex", alignItems:"baseline", justifyContent:"space-between", marginBottom:12 },
  coreGroupLabel:  { fontSize:13, fontWeight:600, color:C.ink },
  coreGroupSub:    { fontSize:11, color:"#aaa", fontFamily:"sans-serif" },
  // Evidence group
  evidenceGroup:        { marginTop:20, paddingTop:20, borderTop:`1px solid ${C.divider}` },
  evidenceGroupHeader:  { display:"flex", alignItems:"flex-start", justifyContent:"space-between", marginBottom:10 },
  evidenceGroupTitleRow:{ display:"flex", alignItems:"center", gap:8 },
  evidenceGroupIcon:    { fontSize:16, opacity:0.65 },
  evidenceGroupTitle:   { fontSize:13, fontWeight:600, color:C.ink },
  evidenceGroupCount:   { fontSize:11, color:"#aaa", fontFamily:"sans-serif", flexShrink:0 },
  evidenceGroupHelper:  { fontSize:12, color:C.sepia, lineHeight:1.65, fontFamily:"sans-serif", margin:"0 0 14px", fontStyle:"italic" },
  groupThumbGrid:  { display:"flex", flexWrap:"wrap", gap:10, marginBottom:14 },
  groupThumbWrap:  { position:"relative", flexShrink:0 },
  groupThumb:      { width:80, height:80, objectFit:"cover", borderRadius:4, display:"block", border:`1px solid ${C.divider}` },
  groupThumbRemove:{ position:"absolute", top:-6, right:-6, width:20, height:20, borderRadius:"50%", background:C.rust, color:"#fff", border:"none", fontSize:14, lineHeight:"20px", textAlign:"center", cursor:"pointer", padding:0, fontFamily:"sans-serif" },
  addEvidenceBtn:  { width:"100%", background:"none", border:`1.5px dashed ${C.divider}`, borderRadius:4, padding:"13px 0", fontSize:13, letterSpacing:"0.03em", cursor:"pointer", color:C.bronze, fontFamily:"sans-serif", textAlign:"center" },
  progressBreakdown:{ color:"#aaa", fontFamily:"sans-serif", fontSize:11 },
  progressGuidance:{ fontSize:12, color:"#aaa", fontFamily:"sans-serif", marginTop:4 },
  // Functional clues section
  optionalInline:  { fontSize:10, letterSpacing:"0.1em", color:"#aaa", fontFamily:"sans-serif", marginLeft:6, textTransform:"uppercase" },
  cluesList:       { display:"flex", flexDirection:"column", gap:2 },
  clueRow:         { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"14px 16px", background:C.card, border:`1px solid ${C.divider}`, borderRadius:6, cursor:"pointer", userSelect:"none", transition:"background 0.15s" },
  clueRowOn:       { background:"#f0f6ee", border:`1px solid #b5c9ae` },
  clueLabel:       { fontSize:14, color:C.ink, lineHeight:1.4, paddingRight:16 },
  // Toggle switch
  toggle:          { flexShrink:0, width:44, height:26, borderRadius:13, background:C.divider, position:"relative", transition:"background 0.2s" },
  toggleOn:        { background:C.sage },
  toggleThumb:     { position:"absolute", top:3, left:3, width:20, height:20, borderRadius:"50%", background:"#fff", boxShadow:"0 1px 3px rgba(0,0,0,0.2)", transition:"transform 0.2s" },
  toggleThumbOn:   { transform:"translateX(18px)" },
  photoCard:   { display:"flex", alignItems:"flex-start", gap:14, background:C.card, border:`1.5px solid ${C.divider}`, borderRadius:6, padding:"14px", position:"relative" },
  photoCardFilled:{ border:`1.5px solid ${C.sage}`, background:"#f4f8f2" },
  photoCardLeft:{ flexShrink:0 },
  photoThumb:  { width:70, height:70, objectFit:"cover", borderRadius:4, display:"block" },
  photoPlaceholder:{ width:70, height:70, borderRadius:4, background:C.parchment, border:`1px dashed ${C.divider}`, display:"flex", alignItems:"center", justifyContent:"center" },
  photoPlaceholderIcon:{ fontSize:22, opacity:0.3 },
  photoCardBody:{ flex:1, minWidth:0 },
  photoCardTitleRow:{ display:"flex", alignItems:"center", gap:8, marginBottom:3 },
  photoCardTitle:{ fontSize:14, fontWeight:600, color:C.ink },
  photoCardCheck:{ fontSize:13, color:C.sage, marginLeft:"auto" },
  photoCardHint:{ fontSize:12, color:C.sepia, fontFamily:"sans-serif", marginBottom:6 },
  photoCardEvidenceHint:{ fontSize:10, color:C.bronze, fontFamily:"sans-serif", marginBottom:10, lineHeight:1.4, letterSpacing:"0.02em" },
  // See example button — small, unobtrusive, inside card title row
  exampleBtn: { background:"none", border:`1px solid ${C.bronze}`, color:C.bronze, padding:"2px 8px", fontSize:10, cursor:"pointer", fontFamily:"sans-serif", borderRadius:2, letterSpacing:"0.06em", marginLeft:6, flexShrink:0, lineHeight:1.6 },
  // Replaces "Optional" on evidence groups
  helpfulTag: { fontSize:9, letterSpacing:"0.1em", textTransform:"uppercase", background:"#f0f4ee", border:`1px solid #b5c4ae`, color:C.sage, padding:"2px 7px", borderRadius:2, fontFamily:"sans-serif", marginLeft:4 },
  evidenceGuidanceBlock:{ marginTop:12, background:"#fdfaf2", border:`1px solid #e8ddb8`, borderRadius:3, padding:"12px 14px", display:"flex", flexDirection:"column", gap:8 },
  evidenceGuidanceTitle:{ fontSize:10, letterSpacing:"0.14em", textTransform:"uppercase", color:C.bronze, fontFamily:"sans-serif", marginBottom:2 },
  evidenceGuidanceRow:  { display:"flex", alignItems:"flex-start", gap:8 },
  evidenceGuidanceIcon: { fontSize:13, color:C.bronze, flexShrink:0, lineHeight:1.5 },
  evidenceGuidanceText: { fontSize:12, color:C.sepia, lineHeight:1.55, fontFamily:"sans-serif" },
  // Two-button upload row
  uploadBtnRow:    { display:"flex", gap:8 },
  uploadBtnCamera: { flex:1, background:C.ink, color:C.parchment, border:"none", borderRadius:4, padding:"9px 0", fontSize:12, cursor:"pointer", fontFamily:"sans-serif", letterSpacing:"0.03em", textAlign:"center" },
  uploadBtnLibrary:{ flex:1, background:"none", color:C.sepia, border:`1.5px solid ${C.divider}`, borderRadius:4, padding:"9px 0", fontSize:12, cursor:"pointer", fontFamily:"sans-serif", letterSpacing:"0.03em", textAlign:"center" },
  // Keep old photoBtn/photoBtnFilled for any remaining uses
  photoBtn:    { flexShrink:0, background:"none", border:`1.5px solid ${C.divider}`, borderRadius:4, padding:"8px 14px", fontSize:12, cursor:"pointer", color:C.sepia, fontFamily:"sans-serif", letterSpacing:"0.06em" },
  photoBtnFilled:{ borderColor:C.sage, color:C.sage },
  optionalTag: { fontSize:9, letterSpacing:"0.12em", textTransform:"uppercase", background:C.parchment, border:`1px solid ${C.divider}`, color:"#999", padding:"1px 6px", borderRadius:2, fontFamily:"sans-serif" },
  progressSection:{ padding:"18px 20px 0" },
  progressBar: { height:4, background:C.divider, borderRadius:2, overflow:"hidden", marginBottom:8 },
  progressFill:{ height:"100%", background:C.bronze, borderRadius:2, transition:"width 0.4s ease" },
  progressText:{ fontSize:13, color:C.sepia, fontFamily:"sans-serif" },
  progressNote:{ color:"#aaa" },
  formStack:   { display:"flex", flexDirection:"column", gap:14 },
  dimRow:      { display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 },
  dimField:    { display:"flex", flexDirection:"column", gap:4 },
  formField:   { display:"flex", flexDirection:"column", gap:4 },
  fieldLabel:  { fontSize:11, letterSpacing:"0.08em", textTransform:"uppercase", color:C.sepia, fontFamily:"sans-serif" },
  fieldInput:  { border:`1px solid ${C.divider}`, background:C.card, padding:"11px 12px", fontSize:14, color:C.ink, fontFamily:"'Georgia',serif", borderRadius:4, outline:"none", WebkitAppearance:"none" },
  fieldTA:     { minHeight:72, resize:"vertical" },
  errorBox:    { background:"#fdf0ec", border:`1px solid ${C.rust}`, color:C.rust, padding:"10px 14px", borderRadius:4, fontSize:13, fontFamily:"sans-serif" },
  // ── Structured phase error card ──────────────────────────────
  phaseErrorCard:       { background:"#fdf0ec", border:`2px solid ${C.rust}`, borderRadius:4, padding:"20px 22px", marginBottom:16 },
  phaseErrorHeader:     { display:"flex", alignItems:"flex-start", gap:12, marginBottom:10 },
  phaseErrorIcon:       { fontSize:20, color:C.rust, flexShrink:0, lineHeight:1.2 },
  phaseErrorTitle:      { fontSize:15, fontWeight:700, color:C.rust, fontFamily:"sans-serif" },
  phaseErrorPhase:      { fontSize:12, color:C.sepia, fontFamily:"sans-serif", marginTop:2 },
  phaseErrorType:       { fontSize:11, letterSpacing:"0.12em", textTransform:"uppercase", color:C.rust, fontFamily:"sans-serif", marginBottom:6, opacity:0.7 },
  phaseErrorMsg:        { fontSize:13, color:C.ink, lineHeight:1.6, marginBottom:8 },
  phaseErrorRetry:      { fontSize:11, color:"#a05020", fontFamily:"sans-serif", marginBottom:8, fontStyle:"italic" },
  phaseErrorDebugToggle:{ background:"none", border:`1px solid ${C.rust}`, color:C.rust, padding:"5px 12px", fontSize:11, cursor:"pointer", fontFamily:"sans-serif", borderRadius:2, letterSpacing:"0.06em", marginTop:4 },
  phaseErrorDebugPanel: { marginTop:14, background:"rgba(26,20,16,0.04)", border:`1px solid ${C.divider}`, borderRadius:2, padding:"14px 16px" },
  debugRow:             { display:"flex", alignItems:"flex-start", gap:16, padding:"5px 0", borderBottom:`1px solid ${C.divider}` },
  debugRowStack:        { display:"flex", flexDirection:"column", gap:6, padding:"8px 0" },
  debugKey:             { width:120, fontSize:11, fontWeight:600, color:C.sepia, fontFamily:"sans-serif", letterSpacing:"0.06em", textTransform:"uppercase", flexShrink:0, paddingTop:1 },
  debugVal:             { fontSize:12, color:C.ink, fontFamily:"monospace", lineHeight:1.5, wordBreak:"break-word" },
  debugRaw:             { fontSize:10, color:C.sepia, fontFamily:"monospace", lineHeight:1.5, background:"rgba(26,20,16,0.06)", padding:"10px 12px", borderRadius:2, overflowX:"auto", whiteSpace:"pre-wrap", wordBreak:"break-word", maxHeight:240, overflowY:"auto", margin:0 },
  analyzeSection:{ padding:"24px 20px 0", display:"flex", flexDirection:"column", gap:10 },
  analyzeBtn:  { width:"100%", background:C.ink, color:C.parchment, border:"none", padding:"18px 0", fontSize:16, letterSpacing:"0.06em", cursor:"pointer", fontFamily:"'Georgia',serif", borderRadius:4, textAlign:"center" },
  analyzeBtnDisabled:{ background:C.divider, color:C.sepia, cursor:"not-allowed" },
  analyzeHint: { textAlign:"center", fontSize:12, color:"#aaa", margin:0, fontFamily:"sans-serif" },
  analysisScreen:{ minHeight:"calc(100vh - 56px)", background:C.cream, display:"flex", alignItems:"flex-start", justifyContent:"center", padding:"0 0 40px" },
  analysisScreenInner:{ width:"100%", maxWidth:560, padding:"32px 20px 0" },
  analysisHeader:{ textAlign:"center", marginBottom:32 },
  analysisLogo:{ fontSize:30, color:C.bronze, marginBottom:12 },
  analysisTitle:{ fontSize:22, fontWeight:400, margin:"0 0 6px" },
  analysisSubtitle:{ fontSize:13, color:C.sepia, margin:0, fontFamily:"sans-serif" },
  analysisPhasesWrap:{ display:"flex", flexDirection:"column" },
  analysisPhaseRow:{ display:"flex", gap:16, minHeight:64 },
  analysisPhaseRowActive:{},
  analysisPhaseLeft:{ display:"flex", flexDirection:"column", alignItems:"center", flexShrink:0, width:36 },
  analysisPhaseCircle:{ width:36, height:36, borderRadius:"50%", border:`2px solid ${C.divider}`, display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0, background:C.cream, zIndex:1 },
  analysisPhaseCircleDone:{ background:C.sage, borderColor:C.sage, color:"#fff", fontWeight:700, fontSize:14 },
  analysisPhaseCircleActive:{ background:C.bronze, borderColor:C.bronze, color:"#fff" },
  analysisConnector:{ flex:1, width:2, background:C.divider, margin:"2px 0" },
  analysisConnectorDone:{ background:C.sage },
  analysisPhaseRight:{ flex:1, paddingBottom:20, paddingTop:6 },
  analysisPhaseName:{ fontSize:14, fontWeight:600, marginBottom:3 },
  analysisPhaseActive:{ color:C.bronze },
  analysisPhaseDone:{ color:C.sage },
  analysisPhasePending:{ color:"#bbb" },
  analysisPhaseDesc:{ fontSize:12, fontFamily:"sans-serif", lineHeight:1.5, color:"#aaa" },
  analysisPhaseNum:{ fontSize:10, fontFamily:"monospace", color:C.sepia },
  spinner:     { display:"inline-block", fontSize:16 },
  analysisFootnote:{ textAlign:"center", fontSize:11, color:"#bbb", fontFamily:"sans-serif", marginTop:8, padding:"0 20px" },
  reportWrap:  { maxWidth:980, margin:"0 auto", padding:"28px 20px 48px" },
  reportHeader:{ marginBottom:24, borderBottom:`1px solid ${C.divider}`, paddingBottom:20 },
  reportTitle: { fontSize:"clamp(22px, 5vw, 34px)", fontWeight:400, margin:"6px 0 12px", lineHeight:1.2, letterSpacing:"-0.01em" },
  metaRow:     { display:"flex", flexWrap:"wrap", gap:7 },

  // ── Professional appraisal summary styles ──────────────────
  appraisalCard:       { background:C.card, border:`1.5px solid ${C.divider}`, borderRadius:4, padding:"22px 24px" },
  appraisalEyebrow:    { fontSize:10, letterSpacing:"0.18em", textTransform:"uppercase", color:C.bronze, fontFamily:"sans-serif", marginBottom:14 },
  appraisalIdRow:      { display:"flex", alignItems:"flex-start", justifyContent:"space-between", gap:12, marginBottom:16 },
  appraisalIdMain:     { flex:1 },
  appraisalIdLabel:    { fontSize:11, letterSpacing:"0.1em", textTransform:"uppercase", color:C.sepia, fontFamily:"sans-serif", marginBottom:4 },
  appraisalIdValue:    { fontSize:"clamp(17px,4vw,22px)", color:C.ink, lineHeight:1.3, fontWeight:400 },
  appraisalClassChip:  { fontSize:11, background:"#eef2eb", border:`1px solid #b5c4ae`, color:C.sage, padding:"3px 10px", borderRadius:2, fontFamily:"sans-serif", letterSpacing:"0.06em", flexShrink:0, alignSelf:"flex-start", marginTop:4 },
  appraisalMetaRow:    { display:"flex", flexWrap:"wrap", gap:20, marginBottom:16, paddingBottom:16, borderBottom:`1px solid ${C.divider}` },
  appraisalMeta:       { display:"flex", flexDirection:"column", gap:3 },
  appraisalMetaLabel:  { fontSize:10, letterSpacing:"0.12em", textTransform:"uppercase", color:C.sepia, fontFamily:"sans-serif" },
  appraisalMetaValue:  { fontSize:15, color:C.ink, fontWeight:400 },
  appraisalConfValue:  { fontWeight:600 },
  appraisalReason:     { fontSize:14, color:C.sepia, lineHeight:1.7, fontStyle:"italic" },

  appraisalSection:    { display:"flex", flexDirection:"column", gap:12 },
  appraisalSectionTitle:{ fontSize:11, letterSpacing:"0.16em", textTransform:"uppercase", color:C.bronze, fontFamily:"sans-serif" },

  // Evidence detected — chip cloud
  clueCloud:      { display:"flex", flexWrap:"wrap", gap:8 },
  clueChip:       { fontSize:12, padding:"5px 12px", borderRadius:2, border:"1px solid", fontFamily:"sans-serif", lineHeight:1.4 },
  clueChipNormal: { background:C.card, borderColor:C.divider, color:C.ink },
  clueChipLow:    { background:"#fdfaf4", borderColor:"#e0d4b0", color:C.sepia, opacity:0.8 },
  clueChipLowMark:{ color:C.bronze, fontWeight:700 },
  clueCloudNote:  { fontSize:10, color:"#aaa", fontFamily:"sans-serif", marginTop:2 },

  // Evidence strength grid
  strengthGrid:     { display:"flex", flexDirection:"column", gap:8 },
  strengthRow:      { display:"flex", alignItems:"center", justifyContent:"space-between", padding:"8px 0", borderBottom:`1px solid ${C.divider}` },
  strengthRowLabel: { fontSize:13, color:C.ink },
  strengthBadge:    { fontSize:11, padding:"3px 12px", borderRadius:2, border:"1px solid", fontFamily:"sans-serif", letterSpacing:"0.06em", fontWeight:600 },

  // Conflicting signals
  conflictSignalList: { listStyle:"none", padding:0, margin:0, display:"flex", flexDirection:"column", gap:8 },
  conflictSignalItem: { display:"flex", alignItems:"flex-start", gap:10, fontSize:13, color:C.sepia, lineHeight:1.6 },
  conflictSignalDot:  { color:"#c8903a", flexShrink:0, marginTop:2, fontSize:11 },

  // What would improve confidence
  improvementList: { listStyle:"none", padding:0, margin:0, display:"flex", flexDirection:"column", gap:9 },
  improvementItem: { display:"flex", alignItems:"flex-start", gap:10, fontSize:13, color:C.sepia, lineHeight:1.6, fontFamily:"'Georgia',serif" },
  improvementIcon: { color:C.sage, flexShrink:0, fontWeight:700, marginTop:1, fontSize:13, fontFamily:"sans-serif" },
  metaBadge:   { fontSize:11, background:C.card, border:`1px solid ${C.divider}`, color:C.sepia, padding:"4px 12px", borderRadius:2, fontFamily:"sans-serif", letterSpacing:"0.05em" },
  metaBadgeDark:{ background:C.ink, color:C.parchment, border:"none" },
  metaBadgeClass:{ background:"#eef2eb", borderColor:"#b5c4ae", color:C.sage },
  metaBadgeWarn:{ background:"#fdf0ec", borderColor:"#e8b090", color:C.rust },
  tabBar:      { display:"flex", overflowX:"auto", borderBottom:`1px solid ${C.divider}`, marginBottom:24, WebkitOverflowScrolling:"touch" },
  tabBtn:      { background:"none", border:"none", padding:"11px 18px", fontSize:13, letterSpacing:"0.05em", cursor:"pointer", color:C.sepia, fontFamily:"sans-serif", borderBottom:"2px solid transparent", whiteSpace:"nowrap", flexShrink:0 },
  tabActive:   { color:C.ink, borderBottomColor:C.ink },
  tabContent:  { display:"flex", flexDirection:"column", gap:20 },
  quadGrid:    { display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:12 },
  quadCard:    { background:C.card, border:`1px solid ${C.divider}`, padding:"16px 18px", borderRadius:4 },
  quadLabel:   { fontSize:9, letterSpacing:"0.16em", textTransform:"uppercase", color:C.bronze, marginBottom:5, fontFamily:"sans-serif" },
  quadVal:     { fontSize:15, color:C.ink, lineHeight:1.3 },
  block:       { background:C.card, border:`1px solid ${C.divider}`, padding:"18px 20px", borderRadius:4 },
  blockTitle:  { fontSize:10, letterSpacing:"0.16em", textTransform:"uppercase", color:C.bronze, marginBottom:12, fontFamily:"sans-serif" },
  evidList:    { listStyle:"none", padding:0, margin:0, display:"flex", flexDirection:"column", gap:7 },
  evidItem:    { display:"flex", alignItems:"flex-start", gap:8, fontSize:13, lineHeight:1.6 },
  dotGreen:    { color:C.sage, flexShrink:0, marginTop:2 },
  dotAmber:    { color:C.rust, flexShrink:0, marginTop:2 },
  summaryPara: { fontSize:13, lineHeight:1.8, color:C.sepia, margin:0 },
  scoreGrid:   { display:"flex", flexDirection:"column", gap:10 },
  scoreRow:    { display:"flex", alignItems:"center", gap:10 },
  scoreLabel:  { width:110, fontSize:11, color:C.sepia, fontFamily:"sans-serif", flexShrink:0 },
  scoreBarWrap:{ flex:1, height:5, background:C.divider, borderRadius:3, overflow:"hidden" },
  scoreBarFill:{ height:"100%", background:C.bronze, borderRadius:3, transition:"width 0.6s" },
  scoreBarNeg: { background:C.rust },
  scoreNums:   { width:64, textAlign:"right", fontSize:11, fontFamily:"monospace", color:C.sepia },
  scoreOpp:    { color:"#bbb" },
  scoreTotalRow:{ display:"flex", justifyContent:"space-between", borderTop:`1px solid ${C.divider}`, paddingTop:9, marginTop:3, fontSize:12, color:C.ink },
  scoreTotalVal:{ fontWeight:700, color:C.bronze, fontFamily:"monospace" },
  evidField:   { marginBottom:9, fontSize:12 },
  evidKey:     { fontWeight:600, color:C.sepia, fontFamily:"sans-serif", fontSize:10, letterSpacing:"0.06em", textTransform:"uppercase", marginRight:5 },
  evidVal:     { color:C.ink },
  subList:     { margin:"4px 0 0 12px", padding:0, listStyle:"disc", color:C.sepia },
  subItem:     { fontSize:11, lineHeight:1.6, marginBottom:2 },
  hwTable:     { marginTop:10, border:`1px solid ${C.divider}`, borderRadius:2, overflow:"hidden" },
  hwHead:      { display:"grid", gridTemplateColumns:"2fr 2fr 1fr 1fr 1fr", gap:6, padding:"6px 10px", background:C.parchment, fontSize:9, letterSpacing:"0.1em", color:C.sepia, fontFamily:"sans-serif", textTransform:"uppercase" },
  hwRow:       { display:"grid", gridTemplateColumns:"2fr 2fr 1fr 1fr 1fr", gap:6, padding:"8px 10px", borderTop:`1px solid ${C.divider}`, fontSize:11 },
  conflictCard:{ background:"#fef9f4", border:`1px solid #e8d5b8`, borderRadius:2, padding:"12px 14px", marginBottom:9 },
  conflictTypeTag:{ fontSize:9, letterSpacing:"0.14em", textTransform:"uppercase", color:C.bronze, fontFamily:"sans-serif", marginBottom:5 },
  conflictText:{ fontSize:12, color:C.ink, marginBottom:4, lineHeight:1.5 },
  conflictResolution:{ fontSize:12, color:C.sepia, marginBottom:3, lineHeight:1.5, fontStyle:"italic" },
  conflictRecovery:{ fontSize:11, color:C.sage, fontFamily:"sans-serif", marginBottom:5 },
  conflictFooter:{ display:"flex", alignItems:"center", gap:8, flexWrap:"wrap", marginTop:5 },
  conflictStatus:{ fontSize:10, color:"#aaa", fontFamily:"sans-serif" },
  severityChip:{ fontSize:9, padding:"2px 7px", borderRadius:2, border:"1px solid", fontFamily:"sans-serif", letterSpacing:"0.06em" },
  adjustmentText:{ fontSize:10, color:"#aaa", fontFamily:"monospace" },
  resolvedChip:{ fontSize:10, color:C.sage, fontFamily:"sans-serif", marginLeft:"auto" },
  unresolvedChip:{ fontSize:10, color:C.rust, fontFamily:"sans-serif", marginLeft:"auto" },
  priorityRow: { display:"flex", alignItems:"flex-start", gap:10, padding:"5px 0", borderBottom:`1px solid ${C.divider}` },
  priorityRank:{ width:24, fontSize:10, color:"#aaa", fontFamily:"monospace", flexShrink:0 },
  priorityTier:{ width:140, fontSize:10, color:C.bronze, fontFamily:"sans-serif", flexShrink:0 },
  priorityFinding:{ fontSize:12, color:C.ink, lineHeight:1.5 },
  stageBlock:  { background:C.card, border:`1px solid ${C.divider}`, borderRadius:4, overflow:"hidden", marginBottom:10 },
  stageHead:   { display:"flex", alignItems:"center", gap:10, padding:"11px 16px", borderBottom:`1px solid ${C.divider}`, background:C.parchment },
  stageNum:    { width:24, height:24, borderRadius:"50%", background:C.ink, color:C.parchment, display:"flex", alignItems:"center", justifyContent:"center", fontSize:9, fontFamily:"monospace", flexShrink:0 },
  stageLabel:  { fontSize:12, fontWeight:600, fontFamily:"sans-serif", color:C.ink },
  stageNote:   { fontSize:9, color:"#aaa", fontFamily:"sans-serif", marginTop:1 },
  skippedChip: { marginLeft:"auto", fontSize:10, color:"#aaa", fontFamily:"sans-serif", fontStyle:"italic" },
  stageJson:   { padding:"12px 16px", margin:0, fontSize:10, lineHeight:1.55, color:C.sepia, overflowX:"auto", fontFamily:"monospace", background:"transparent" },
  provisionalBanner:{ background:"#fdf0ec", border:`1px solid #e8b090`, color:C.rust, padding:"9px 14px", borderRadius:2, fontSize:12, fontFamily:"sans-serif", marginBottom:14 },
  valGrid:     { display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))", gap:12 },
  valCard:     { background:C.card, border:`1px solid ${C.divider}`, padding:"16px 18px", borderRadius:4 },
  valLane:     { fontSize:9, letterSpacing:"0.16em", textTransform:"uppercase", color:C.bronze, marginBottom:5, fontFamily:"sans-serif" },
  valRange:    { fontSize:20, color:C.ink, marginBottom:6 },
  valRationale:{ fontSize:11, color:C.sepia, lineHeight:1.6, fontFamily:"sans-serif" },
  reportFooter:{ marginTop:36, borderTop:`1px solid ${C.divider}`, paddingTop:20, display:"flex", alignItems:"center", justifyContent:"space-between", flexWrap:"wrap", gap:10 },
  newCaseBtn:  { background:"none", border:`1px solid ${C.divider}`, padding:"9px 16px", fontSize:13, cursor:"pointer", color:C.sepia, fontFamily:"'Georgia',serif", borderRadius:2 },
  footerNote:  { fontSize:10, color:C.divider, fontFamily:"sans-serif" },
  vsSummaryRow:    { display:"flex", gap:10, marginBottom:12, flexWrap:"wrap" },
  vsStatBox:       { flex:"1 1 70px", background:C.parchment, border:`1px solid ${C.divider}`, borderRadius:3, padding:"10px 14px", textAlign:"center" },
  vsStatBoxWarn:   { background:"#fdf0ec", borderColor:"#e8b090" },
  vsStatNum:       { fontSize:20, fontWeight:400, color:C.ink, marginBottom:2 },
  vsStatLabel:     { fontSize:9, letterSpacing:"0.12em", textTransform:"uppercase", color:C.sepia, fontFamily:"sans-serif" },
  vsNonDestructive:{ fontSize:10, color:C.sage, fontFamily:"sans-serif", fontStyle:"italic", marginTop:7 },
  hardNegRow:      { display:"flex", alignItems:"center", gap:12, padding:"7px 0", borderBottom:`1px solid ${C.divider}`, flexWrap:"wrap" },
  hardNegClue:     { fontSize:12, color:C.rust, fontFamily:"monospace", minWidth:160 },
  hardNegConf:     { fontSize:11, color:C.sepia, fontFamily:"monospace" },
  hardNegRegion:   { fontSize:10, color:"#aaa", fontFamily:"sans-serif", marginLeft:"auto" },
  vsObsHeader:     { display:"flex", gap:6, padding:"5px 0", borderBottom:`1px solid ${C.divider}`, fontSize:9, letterSpacing:"0.1em", textTransform:"uppercase", color:C.sepia, fontFamily:"sans-serif", marginBottom:3 },
  vsObsRow:        { display:"flex", alignItems:"flex-start", gap:6, padding:"7px 0", borderBottom:`1px solid ${C.divider}` },
  vsObsRowReviewed:{ background:"#f5fbf4" },
  vsObsClue:       { fontSize:11, color:C.bronze, fontFamily:"monospace", flexShrink:0 },
  vsObsText:       { fontSize:11, color:C.ink, lineHeight:1.5 },
  vsObsNum:        { fontSize:11, fontFamily:"monospace", flexShrink:0, textAlign:"right" },
  vsObsRegion:     { fontSize:10, color:"#aaa", fontFamily:"sans-serif", flexShrink:0 },
  vsReviewedTag:   { fontSize:11, marginLeft:3, flexShrink:0 },
  warnText:        { color:C.rust },
  imageCount:      { fontSize:11, color:C.sepia, fontFamily:"sans-serif" },
};

