/**
 * Canonical forms library for Proof Sleuth. Per Section 6.6 of the
 * architectural synthesis. Forms identify the structural type of furniture
 * being analyzed (cabinet, table, chair, etc.) and are consulted by P3 form
 * identification.
 */
import { CanonicalEntry } from "./entryShape";

export interface FormEntry extends CanonicalEntry {
  category: "form";
  name: string;
  parent_category: string;
  common_conversion_targets?: string[];
  distinguishing_features?: string[];
  regional_period_notes?: string;
}

export const FORMS: FormEntry[] = [
  {
    id: "form_pump_organ_cabinet",
    category: "form",
    name: "pump organ cabinet",
    parent_category: "specialized",
    date_floor: 1870,
    date_ceiling: 1900,
    common_conversion_targets: ["desk", "cabinet", "bar"],
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_drop_leaf_table",
    category: "form",
    name: "drop-leaf table",
    parent_category: "table",
    date_floor: 1700,
    date_ceiling: 1999,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_gate_leg_table",
    category: "form",
    name: "gate-leg table",
    parent_category: "table",
    date_floor: 1600,
    date_ceiling: 1999,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_washstand",
    category: "form",
    name: "washstand",
    parent_category: "case_piece",
    date_floor: 1820,
    date_ceiling: 1900,
    common_conversion_targets: ["bathroom_vanity"],
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_sideboard",
    category: "form",
    name: "sideboard",
    parent_category: "case_piece",
    date_floor: 1780,
    date_ceiling: 1900,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_buffet",
    category: "form",
    name: "buffet",
    parent_category: "case_piece",
    date_floor: 1870,
    date_ceiling: 1930,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_server",
    category: "form",
    name: "server",
    parent_category: "case_piece",
    date_floor: 1870,
    date_ceiling: 1930,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_dresser",
    category: "form",
    name: "dresser",
    parent_category: "case_piece",
    date_floor: 1800,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_chest_of_drawers",
    category: "form",
    name: "chest of drawers",
    parent_category: "case_piece",
    date_floor: 1700,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_blanket_chest",
    category: "form",
    name: "blanket chest",
    parent_category: "case_piece",
    date_floor: 1700,
    date_ceiling: 1999,
    common_conversion_targets: ["bench"],
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_pie_safe",
    category: "form",
    name: "pie safe",
    parent_category: "case_piece",
    date_floor: 1820,
    date_ceiling: 1880,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_jelly_cupboard",
    category: "form",
    name: "jelly cupboard",
    parent_category: "case_piece",
    date_floor: 1820,
    date_ceiling: 1880,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
    notes: "Date range narrowed from original \"1800s\" (full century) to 1820-1880 per appraiser call during Session 2 migration: post-Federal vernacular form, peak production through Victorian, declining as kitchen design shifted.",
  },
  {
    id: "form_china_cabinet",
    category: "form",
    name: "china cabinet",
    parent_category: "case_piece",
    date_floor: 1880,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_bookcase",
    category: "form",
    name: "bookcase",
    parent_category: "case_piece",
    date_floor: 1700,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_wardrobe",
    category: "form",
    name: "wardrobe",
    parent_category: "case_piece",
    date_floor: 1800,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_writing_table",
    category: "form",
    name: "writing table",
    parent_category: "desk",
    date_floor: 1700,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_secretary_desk",
    category: "form",
    name: "secretary desk",
    parent_category: "desk",
    date_floor: 1700,
    date_ceiling: 1999,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_slant_front_desk",
    category: "form",
    name: "slant-front desk",
    parent_category: "desk",
    date_floor: 1700,
    date_ceiling: 1899,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_windsor_chair",
    category: "form",
    name: "Windsor chair",
    parent_category: "seating",
    date_floor: 1700,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_rocking_chair",
    category: "form",
    name: "rocking chair",
    parent_category: "seating",
    date_floor: 1800,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_milking_stool",
    category: "form",
    name: "milking stool",
    parent_category: "seating",
    date_floor: 1800,
    date_ceiling: 1920,
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_sewing_machine_cabinet",
    category: "form",
    name: "sewing machine cabinet",
    parent_category: "specialized",
    date_floor: 1870,
    date_ceiling: 1910,
    common_conversion_targets: ["nightstand", "side_table"],
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
  {
    id: "form_icebox",
    category: "form",
    name: "icebox",
    parent_category: "specialized",
    date_floor: 1880,
    date_ceiling: 1920,
    common_conversion_targets: ["bar", "beverage_cabinet"],
    positive_authority: 7,
    hard_negative_authority: 7,
    migration_status: "partial",
  },
];
