/**
 * Corpus reconciliation ledger generator.
 *
 * Single regenerable source of truth tying each fixture to its provenance
 * (S-scan id), failure mechanisms (M-tags), triage batch (T-tags) and
 * issue/fix numbers (#-tags), plus an S-series disposition audit.
 *
 *   node --import tsx scripts/_tagmap.ts            # print to stdout
 *   node --import tsx scripts/_tagmap.ts --write    # (re)write docs/corpus-ledger.md
 */
import { readFileSync, writeFileSync } from "node:fs";
import { SESSION_SCANS } from "../tests/fixtures/sessionScans";

const uniq = (re: RegExp, s: string) => Array.from(new Set(s.match(re) || [])).sort();
const sId = (s: string) => uniq(/\bS[0-9]{3}/g, s);

const ENGINE_FILES = [
  "lib/engine.ts",
  "lib/engineDatingOverlap.ts",
  "lib/engineStyleReconciliation.ts",
];
const engineSrc = ENGINE_FILES.map((f) => readFileSync(f, "utf8")).join("\n");
const fixtureSrc = readFileSync("tests/fixtures/sessionScans.ts", "utf8");

const engineSids = new Set(sId(engineSrc));
const fixtureCommentSids = new Set(sId(fixtureSrc)); // notes + authoring comments

const mFix: Record<string, string[]> = {};
const noteSidFix: Record<string, string[]> = {};
type Row = { label: string; S: string[]; M: string[]; T: string[]; H: string[]; form: string; date: string; conf: string };
const rows: Row[] = [];

for (const s of SESSION_SCANS as any[]) {
  const n = s.note || "";
  const M = uniq(/\bM[0-9]+[a-z-]*/g, n);
  const T = uniq(/\bT[0-9][a-z]/g, n);
  const H = uniq(/#[0-9]+[a-z-]*/g, n);
  const S = sId(n);
  rows.push({
    label: s.label, S, M, T, H,
    form: s.asSeen?.display || s.asSeen?.formId || "—",
    date: s.asSeen?.dateRange || "—",
    conf: s.asSeen?.confidence || "—",
  });
  for (const m of M) (mFix[m] ??= []).push(s.label);
  for (const x of S) (noteSidFix[x] ??= []).push(s.label);
}

const mechRows = Object.entries(mFix).sort((a, b) => b[1].length - a[1].length);

function sStatus(id: string): { disp: string; where: string } {
  const inEngine = engineSids.has(id);
  const inFixNote = !!noteSidFix[id];
  const inFixSrc = fixtureCommentSids.has(id);
  const where: string[] = [];
  if (inEngine) where.push("engine guard");
  if (inFixNote) where.push(`fixture note (${noteSidFix[id].join(", ")})`);
  else if (inFixSrc) where.push("fixture comment");
  if (inEngine) return { disp: "FIXED (shipped guard)", where: where.join("; ") };
  if (inFixNote || inFixSrc) return { disp: "TRACKED (fixture)", where: where.join("; ") };
  return { disp: "UNTRACED", where: "— not referenced anywhere on disk" };
}

const lines: string[] = [];
const p = (s = "") => lines.push(s);

p("# Corpus reconciliation ledger");
p();
p("> GENERATED by `scripts/_tagmap.ts --write` from `tests/fixtures/sessionScans.ts`");
p("> and the engine source. Do not hand-edit the tables; rerun the generator.");
p();
p("## Why this exists — the numbering systems");
p();
p("Five independent numbering schemes accreted across the stress test and never");
p("got reconciled into one place. Three of them use bare `#N`, so counts drift by");
p("which source you parse. This ledger is the single forward-reconciled view.");
p();
p("| scheme | range | home | counts |");
p("|---|---|---|---|");
p("| **S-scan ids** | S001–S017 | inline tags in fixture notes + engine comments | the original 17 stress scans |");
p("| **Corpus fixtures** | 28 | `tests/fixtures/sessionScans.ts` | regression specimens (outgrew the S-series) |");
p("| **Stress-test issues** | #1–#17 | `docs/stress-test-findings.md` | ranked fix queue (NOT scans) |");
p("| **Fix-queue / GitHub** | #1–#10, #111-b, … | fixture notes + commits | candidate + shipped fixes |");
p("| **Mechanisms / triage** | M1–M12, T1a–T2b | fixture notes | failure mechanisms + triage batches |");
p();
p("The phantom \"17 vs 28\": **S-numbering froze at S017** (the original scan");
p("session) while the corpus kept growing to **28** as later mechanism-isolation");
p("and control fixtures were authored without S-ids. The two counts were never");
p("meant to match.");
p();
p("## S-series disposition audit (S001–S017)");
p();
p("`FIXED` = the scan motivated a guard now live in engine source. `TRACKED` =");
p("a fixture pins its behavior but no dedicated guard cites it. `UNTRACED` = no");
p("reference anywhere on disk (triaged-and-dropped, or provenance lost).");
p();
p("| S-id | disposition | referenced in |");
p("|---|---|---|");
let untraced: string[] = [];
for (let i = 1; i <= 17; i++) {
  const id = "S" + String(i).padStart(3, "0");
  const { disp, where } = sStatus(id);
  if (disp === "UNTRACED") untraced.push(id);
  p(`| ${id} | ${disp} | ${where} |`);
}
p();
p(`**Disposition gap:** ${untraced.length} of 17 scans are UNTRACED — ${untraced.join(", ")}.`);
p("These produced no fixture and no cited guard; confirm each was a benign");
p("triage (no action needed) rather than a dropped finding.");
p();
p("## Mechanism tally (distinct fixtures)");
p();
p("Counted once per specimen (not per note-mention).");
p();
p("| mechanism | # fixtures | specimens |");
p("|---|---|---|");
for (const [m, fx] of mechRows) p(`| ${m} | ${fx.length} | ${fx.join(", ")} |`);
p();
p("## Per-fixture map (28)");
p();
p("| fixture | S | M | T | # | as-seen form | as-seen date | conf |");
p("|---|---|---|---|---|---|---|---|");
for (const r of rows)
  p(`| ${r.label} | ${r.S.join(" ") || "—"} | ${r.M.join(" ") || "—"} | ${r.T.join(" ") || "—"} | ${r.H.join(" ") || "—"} | ${r.form} | ${r.date} | ${r.conf} |`);
p();

const out = lines.join("\n") + "\n";
if (process.argv.includes("--write")) {
  writeFileSync("docs/corpus-ledger.md", out);
  console.log(`wrote docs/corpus-ledger.md (${rows.length} fixtures, ${untraced.length} untraced S-ids)`);
} else {
  process.stdout.write(out);
}
